apiVersion: v2
name: ceph-mgr-endpoint-controller
description: A Kubernetes controller that discovers Ceph Manager services and creates corresponding EndpointSlices
type: application
version: "0.3.1"
appVersion: "0.3.1"
kubeVersion: ">=1.29.0"
