image:
  repository: ghcr.io/josh/ceph-mgr-endpoint-controller
  tag: ""
  pullPolicy: IfNotPresent

ceph:
  secret:
    name: ceph-mgr-endpoint-controller-secret
    userID: userID
    userKey: userKey
  config:
    create: true
    name: ceph-config
    clusterID: ""
    monitors: []

controller:
  mode: deployment
  serviceName: ceph-mgr
  dashboardSliceName: ceph-mgr-dashboard
  prometheusSliceName: ceph-mgr-prometheus
  interval: 30s
  debug: false
  cronjob:
    schedule: "*/5 * * * *"
    concurrencyPolicy: Forbid
    successfulJobsHistoryLimit: 1
    failedJobsHistoryLimit: 1

service:
  create: true
  ports:
    dashboard: 8443
    prometheus: 9283

serviceAccount:
  create: true
  name: ""

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
