image:
  repository: ghcr.io/josh/ceph-mgr-endpoint-controller
  tag: v0.2.1
  pullPolicy: IfNotPresent

ceph:
  id: admin
  configPath: ""
  keyringPath: ""
  extraArgs: []
  config:
    create: true
    name: ceph-config
    content: ""
    clusterID: ""
    monitors: []
  keyring:
    type: keyring
    name: ceph-keyring

controller:
  mode: deployment
  serviceName: ceph-mgr
  dashboardSliceName: ceph-mgr-dashboard
  prometheusSliceName: ceph-mgr-prometheus
  interval: 30s
  debug: false
  cronjob:
    schedule: "*/5 * * * *"
    concurrencyPolicy: Forbid
    successfulJobsHistoryLimit: 1
    failedJobsHistoryLimit: 1

service:
  create: true
  ports:
    dashboard: 8443
    prometheus: 9283

serviceAccount:
  create: true
  name: ""

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
