{{- if .Values.cephConfig.configMap.create }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.cephConfig.configMap.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ceph-mgr-endpoint-controller.labels" . | nindent 4 }}
data:
  ceph.conf: |
    {{- if .Values.cephConfig.configMap.content }}
    {{- .Values.cephConfig.configMap.content | nindent 4 }}
    {{- else }}
    [global]
    {{- if .Values.cephConfig.configMap.clusterID }}
    fsid = {{ .Values.cephConfig.configMap.clusterID }}
    {{- end }}
    {{- if .Values.cephConfig.configMap.monitors }}
    mon_host = {{ join "," .Values.cephConfig.configMap.monitors }}
    {{- end }}
    {{- end }}
{{- end }}
