{{- if .Values.ceph.config.create }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.ceph.config.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ceph-mgr-endpoint-controller.labels" . | nindent 4 }}
data:
  ceph.conf: |
    [global]
    {{- if .Values.ceph.config.clusterID }}
    fsid = {{ .Values.ceph.config.clusterID }}
    {{- end }}
    {{- if .Values.ceph.config.monitors }}
    mon_host = {{ join "," .Values.ceph.config.monitors }}
    {{- end }}
{{- end }}
