apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ceph-mgr-endpoint-controller.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ceph-mgr-endpoint-controller.labels" . | nindent 4 }}
data:
  config.json: {{ dict "debug" .Values.controller.debug "interval" .Values.controller.interval | toJson | quote }}
