apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ceph-mgr-endpoint-controller.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ceph-mgr-endpoint-controller.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "ceph-mgr-endpoint-controller.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "ceph-mgr-endpoint-controller.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "ceph-mgr-endpoint-controller.serviceAccountName" . }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
        runAsGroup: 65534
        fsGroup: 65534
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: controller
          image: "{{ .Values.image.repository }}:{{ include "ceph-mgr-endpoint-controller.imageTag" . }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: ceph-config
              mountPath: /etc/ceph
              readOnly: true
            - name: ceph-secret
              mountPath: /var/run/secrets/ceph
              readOnly: true
            - name: controller-config
              mountPath: /etc/ceph-mgr-endpoint-controller.json
              subPath: config.json
              readOnly: true
      volumes:
        - name: controller-config
          configMap:
            name: {{ include "ceph-mgr-endpoint-controller.fullname" . }}-config
        - name: ceph-config
          projected:
            sources:
              - configMap:
                  name: {{ .Values.ceph.config.name }}
        - name: ceph-secret
          secret:
            secretName: {{ .Values.ceph.secret.name }}
            items:
              - key: {{ .Values.ceph.secret.userID }}
                path: userID
              - key: {{ .Values.ceph.secret.userKey }}
                path: userKey
