apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "ceph-mgr-endpoint-controller.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ceph-mgr-endpoint-controller.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["get"]
  - apiGroups: ["discovery.k8s.io"]
    resources: ["endpointslices"]
    verbs: ["get", "create", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "ceph-mgr-endpoint-controller.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ceph-mgr-endpoint-controller.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "ceph-mgr-endpoint-controller.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "ceph-mgr-endpoint-controller.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
